# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0003_auto_20180918_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='city_name',
            field=models.CharField(default=b'null', max_length=254),
        ),
        migrations.AddField(
            model_name='stadiums',
            name='stadium_ca',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadiums',
            name='stadiumcod',
            field=models.CharField(default=b'null', max_length=254),
        ),
    ]
