# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0004_auto_20180918_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcteams',
            name='AssociationName',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='wcteams',
            name='Continent',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='wcteams',
            name='CountryCode',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='wcteams',
            name='CountryName',
            field=models.CharField(max_length=254),
        ),
    ]
