# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0005_auto_20180918_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wcup',
            old_name='StadiumCode',
            new_name='stadiumcod',
        ),
    ]
