# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0006_auto_20180918_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcup',
            name='MatchName',
            field=models.CharField(max_length=254),
        ),
    ]
