# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0007_auto_20180918_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='Minute',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='PlayerName',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='wcmatch',
            name='MatchLinup',
            field=models.CharField(default=b'null', max_length=254),
        ),
        migrations.AlterField(
            model_name='wcmatch',
            name='Score',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='wcstanding',
            name='WCGroupName',
            field=models.CharField(max_length=254),
        ),
    ]
