# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-19 20:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0008_auto_20180918_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default=b'null', max_length=254)),
                ('fdcouk', models.CharField(default=b'null', max_length=254)),
                ('city', models.CharField(default=b'null', max_length=254)),
                ('stadium', models.CharField(default=b'null', max_length=254)),
                ('capacity', models.BigIntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('country', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'StadClubs',
            },
        ),
    ]
