# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-23 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0012_playerscore_playercountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcup',
            name='MatchNumber',
            field=models.CharField(default=b'null', max_length=254),
        ),
    ]
