# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WC', '0013_auto_20180923_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadclub',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
